### ISSUE TITLE
Fix portfolio cards on mobile

### ISSUE THREAD

**Issue by JacksonBates** [JacksonBates/jacksonbates.github.io#14]
## Note to Hacktoberfest participants

Submit PRs from 1st October to qualify for Hacktoberfest.

## Overview

The portfolio cards are clipped on mobile widths. They should have a comfortable margin.

![site-bug](https://user-images.githubusercontent.com/4337740/94495275-a681a000-0234-11eb-820d-918ba3c035b8.png)

**Comment by oxavibes** [comment]
Hi Jackson, I can help you with this issue 😃

**Comment by JacksonBates** [comment]
Ok @oxavibes, happy hacking! Good luck with the rest of Hacktoberfest :)

**Comment by vidur-ui** [comment]
Hi @JacksonBates I can help you to fix this issue

**Comment by JacksonBates** [comment]
@vidur-ui sorry this is already assigned.
