### ISSUE TITLE
Add Dev Minute playlist to the navigation menu

### ISSUE THREAD

**Issue by JacksonBates** [JacksonBates/jacksonbates.github.io#15]
## Note to Hacktoberfest participants:

Submit your PR after Oct 1st for it to qualify for Hacktoberfest!

## Overview

I'd like the Dev Minute playlist I've started working on to be linked to from the menu on this site.

The label should read "Dev Minute" and come after the "Writing" menu item.

The location the link should redirect to is: https://www.youtube.com/playlist?list=PLyRItRv4aHfPeFpsMP5LU7OVgQJv0dss5

**Comment by EmmaDawsonDev** [comment]
Hi Jackson, can I please have a go at fixing this issue?

**Comment by JacksonBates** [comment]
Yes @emmalearnscode.

Let me know if you need any help getting it set up locally or with the PR.

Good luck with Hacktoberfest!

**Comment by EmmaDawsonDev** [comment]
Brilliant, thanks! And I'll shout if I get stuck :)
